### ISSUE TITLE
Nothing generated when there is @RequestScope component

### ISSUE THREAD

**Issue by pkubowicz** [maciejwalkowiak/spring-boot-startup-report#19]
I have
```
@Component
@RequestScope
```
and this makes me unable to execute. The stack trace is:

```
Exception thrown from ApplicationListener handling ContextClosedEvent
org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'scopedTarget.requestContext': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:383)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1168)
	at com.maciejwalkowiak.spring.boot.startup.TagsResolver.resolveTags(TagsResolver.java:39)
	at com.maciejwalkowiak.spring.boot.startup.Event.create(Event.java:31)
```

Not sure how to fix it. A dirty hack would be to additionally catch ScopeNotActiveException in `TagsResolver.resolveTags`.

**Comment by maciejwalkowiak** [comment]
Thanks @pkubowicz I hit the same problem with `@JobScope` from Spring Batch and found the same workaround.
