### ISSUE TITLE
No qualifying bean of type 'com.maciejwalkowiak.spring.boot.startup.ReportRenderer' available

### ISSUE THREAD

**Issue by jkickic** [maciejwalkowiak/spring-boot-startup-report#5]
Hi Maciej. 
I wanted to try out this tool to check my app but it fails to find the ReportRenderer bean.
I tested on a fresh project out of spring initializer on spring boot versions 2.7.9 (from your dependencies) and 2.6.7 (from my app) and both fail the same when running the unit tests.
Any requirements I should meet to run this?

```
$ java --version
openjdk 17.0.6 2023-01-17
```

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.maciejwalkowiak.spring.boot.startup.ReportRenderer' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351) ~[spring-beans-5.3.25.jar:5.3.25]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.25.jar:5.3.25]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172) ~[spring-context-5.3.25.jar:5.3.25]
        at com.maciejwalkowiak.spring.boot.startup.StartupEventsCustomizer.lambda$customizeContext$0(StartupEventsCustomizer.java:33) ~[spring-boot-startup-report-0.1.0.jar:0.1.0]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.25.jar:5.3.25]
        at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.7.9.jar:2.7.9]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-2.7.9.jar:2.7.9]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

```

**Comment by maciejwalkowiak** [comment]
This means that the autoconfiguration did not kick in. Auto-configuration requires Jackson on the classpath, maybe you can add `spring-boot-starter-web` or `spring-boot-starter-json` do your dependencies and try again?

Or to be sure why the autoconfig didn't run, can you add `debug=true` in application.properties and look at the autoconfiguration report?

**Comment by maciejwalkowiak** [comment]
It does indeed, thanks for hint!

**Comment by maciejwalkowiak** [comment]
Updated https://github.com/maciejwalkowiak/spring-boot-startup-report/commit/2dfeb41afc6d12ba2b60be1da12a9a5043a62dcd
